import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    {
      type: 'autogenerated',
      dirName: 'overview',
    },
  ],
  layoutSidebar: [
    {
      type: 'autogenerated',
      dirName: 'layout',
    },
  ],
  typographySidebar: [
    {
      type: 'autogenerated',
      dirName: 'typography',
    },
  ],
  colorSidebar: [
    {
      type: 'autogenerated',
      dirName: 'color',
    },
  ],
  visualSidebar: [
    {
      type: 'autogenerated',
      dirName: 'visual',
    },
  ],
  responsiveSidebar: [
    {
      type: 'autogenerated',
      dirName: 'responsive',
    },
  ],
  interactiveSidebar: [
    {
      type: 'autogenerated',
      dirName: 'interactive',
    },
  ],
  methodologySidebar: [
    {
      type: 'autogenerated',
      dirName: 'methodology',
    },
  ],
  inboxSidebar: [
    {
      type: 'autogenerated',
      dirName: 'inbox',
    },
  ],
};

export default sidebars;
